SRCDIR = ..

# Test programs to compile, and a list of sources for each.
# To add a new test, put its name on the PROGS list
# and then add a name_SRC line that lists its source files.
PROGS = cat cmp cp echo halt hex-dump ls mcat mcp mkdir pwd rm shell \
	bubsort insult lineup matmult recursor \
    nodnok rndgen knight hanoi snconv sortdig checkseq subsets nsum kjump queen primes \
    editor calc translate replace digset iplog loops bgrun psinfo memstat fsinfo

cat_SRC = cat.c
cmp_SRC = cmp.c
cp_SRC = cp.c
echo_SRC = echo.c
halt_SRC = halt.c
hex-dump_SRC = hex-dump.c
insult_SRC = insult.c
lineup_SRC = lineup.c
ls_SRC = ls.c
recursor_SRC = recursor.c
rm_SRC = rm.c
bubsort_SRC = bubsort.c
matmult_SRC = matmult.c
mcat_SRC = mcat.c
mcp_SRC = mcp.c
mkdir_SRC = mkdir.c
pwd_SRC = pwd.c
shell_SRC = shell.c

nodnok_SRC = nodnok.c
rndgen_SRC = rndgen.c
knight_SRC = knight.c
hanoi_SRC = hanoi.c
snconv_SRC = snconv.c
sortdig_SRC = sortdig.c
checkseq_SRC = checkseq.c
subsets_SRC = subsets.c
nsum_SRC = nsum.c
kjump_SRC = kjump.c
queen_SRC = queen.c
primes_SRC = primes.c

editor_SRC = editor.c
calc_SRC = calc.c
translate_SRC = translate.c
replace_SRC = replace.c
digset_SRC = digset.c
iplog_SRC = iplog.c
loops_SRC = loops.c
bgrun_SRC = bgrun.c
psinfo_SRC = psinfo.c
memstat_SRC = memstat.c
fsinfo_SRC = fsinfo.c

include $(SRCDIR)/Make.config
include $(SRCDIR)/Makefile.userprog
